server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://guest-book-db.cjix2ohrkuio.ap-northeast-2.rds.amazonaws.com:3306/myapp
    username: admin
    password: gg12345$
    driver-class-name: com.mysql.cj.jdbc.Driver